apiVersion: v1
kind: ConfigMap
metadata:
  name: db-ca-cert
  namespace: dataforall
  labels:
    app: dataforall
    component: database
data:
  vultr-db-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIERDCCAqygAwIBAgIUFD/nRKqNgLgTykfBvZZhVX94Tx8wDQYJKoZIhvcNAQEM
    BQAwOjE4MDYGA1UEAwwvMmFlODQ4ODgtODZhMi00NGEwLWI4ZTktZGIyZWQ4ZmQ2
    MzgwIFByb2plY3QgQ0EwHhcNMjYwMjA3MjEyOTQ3WhcNMzYwMjA1MjEyOTQ3WjA6
    MTgwNgYDVQQDDC8yYWU4NDg4OC04NmEyLTQ0YTAtYjhlOS1kYjJlZDhmZDYzODAg
    UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALmzY3Jd
    0xZVdagmOm2KQP3/sxrrvvo5oaMwTISS+6dCUQvRN3Usa6riKoCBzgPypKBrWfYh
    FcNL2L7C7M58un52xI/MYl0jhOJ27JbGsN2dIT54BbGkXkl767SfCdZAwoSudEpE
    zzwqSDGsu9w57VXgtw9ygfFbDQzo8M66mWk1UDllPV/SZDzmswD+K9rRYM2cLueF
    jxeS3YsUyfN8tjcXXPJSwCTNUS+4XC/DrW7Tq9N6WA+fJ4oguqoFxX3oOV6YzhGy
    AOZ0aQ1biqYybkHmKqW558pA2W/k46zVz783LkTdqlRzh1r5suI5JJdaGvxnaoVA
    RUNgTGCzsgDEUFUTT1tDRZvnJHQadmCpXOyrAtLtTEfJNTrEiGV90/t/FwltjLMF
    EoJPMIBEVmI745O9uIs0GO2Ka1KNvTiRuHeZ/CF5oxBkBf3p/BLhOxx3g1MJhIBx
    vq3ZNpr+RiRthg/jA7I7PP4LHZmviBlBgZmDLBAeGCIWxu9gjaa6w6MMwIDAQAB
    o0IwQDAdBgNVHQ4EFgQUR9nMRpdKC7K1MEbOa6xLPCo97OswEgYDVR0TAQH/BAgw
    BgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBADHAiFF8saN8
    anaIiPa5MSu7chPmur49P794Y67cSMPjR9EEcG2IgiSxHeBvHVhLyTSZyOu6k31L
    DpI29MXtlnTVG5ipGLxxM65LBe4mU9zlQv9E3gmNjDNHA24IB8uiqAcQ8pia54vZ
    TvDwyEroqDu3JYSChX2f3V24plPejNJUZW8XUdJWhPbERFz38OsJzIG07UVQQOFE
    8ZeJgoKj44IaVlTpiZw4XCNSI2DLDFZpflpI5PbY2WMUZ0ufkBj5u8upXSEg7yDS
    uq/tBAkdebsR0usw0PParv7HkkIL69qsp+92JuSU6R8g6M5H3V6HQu3Vmxqc2FO5
    sBBujqu1QRBTkoZCNJt777VqpDFpctqtYmcVBhM9ThWccnfJvd99qDNFikmoxlW4
    RFTpLe5yXMUOJWlvzbNmg4NPJQJ6kF8uY/ZKvo7ZH1orKkHD/j3hVv3izt66fFo2
    M9Bt3o+8gCNBqh6eqPTYhDd9WckzmpxihiyR/7725wfpibFZE7G4Cw==
    -----END CERTIFICATE-----
