apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dataforall
  labels:
    app: dataforall
    component: backend
spec:
  type: LoadBalancer
  selector:
    app: dataforall
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
